# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drm_options.ui'
#
# Created: Thu Feb 25 10:54:30 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(531, 739)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.logos = QtGui.QVBoxLayout()
        self.logos.setObjectName(_fromUtf8("logos"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setPixmap(QtGui.QPixmap(_fromUtf8("drm.gif")))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_6.addWidget(self.label_10)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setPixmap(QtGui.QPixmap(_fromUtf8("gnu_radio_scaled.gif")))
        self.label_11.setScaledContents(False)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_6.addWidget(self.label_11)
        self.logos.addLayout(self.horizontalLayout_6)
        spacerItem1 = QtGui.QSpacerItem(20, 14, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.logos.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.logos)
        self.main_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.main_label.setFont(font)
        self.main_label.setObjectName(_fromUtf8("main_label"))
        self.verticalLayout_2.addWidget(self.main_label)
        self.sdc_msc = QtGui.QVBoxLayout()
        self.sdc_msc.setObjectName(_fromUtf8("sdc_msc"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.msc_16 = QtGui.QRadioButton(self.groupBox)
        self.msc_16.setObjectName(_fromUtf8("msc_16"))
        self.horizontalLayout_5.addWidget(self.msc_16)
        self.msc_64 = QtGui.QRadioButton(self.groupBox)
        self.msc_64.setObjectName(_fromUtf8("msc_64"))
        self.horizontalLayout_5.addWidget(self.msc_64)
        self.sdc_msc.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.sdc_4 = QtGui.QRadioButton(self.groupBox_2)
        self.sdc_4.setObjectName(_fromUtf8("sdc_4"))
        self.horizontalLayout_7.addWidget(self.sdc_4)
        self.sdc_16 = QtGui.QRadioButton(self.groupBox_2)
        self.sdc_16.setObjectName(_fromUtf8("sdc_16"))
        self.horizontalLayout_7.addWidget(self.sdc_16)
        self.sdc_msc.addWidget(self.groupBox_2)
        self.verticalLayout_2.addLayout(self.sdc_msc)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.rm_label = QtGui.QLabel(self.centralwidget)
        self.rm_label.setObjectName(_fromUtf8("rm_label"))
        self.verticalLayout.addWidget(self.rm_label)
        self.rm_box = QtGui.QComboBox(self.centralwidget)
        self.rm_box.setObjectName(_fromUtf8("rm_box"))
        self.verticalLayout.addWidget(self.rm_box)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem2 = QtGui.QSpacerItem(121, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.so_label = QtGui.QLabel(self.centralwidget)
        self.so_label.setObjectName(_fromUtf8("so_label"))
        self.verticalLayout_5.addWidget(self.so_label)
        self.so_box = QtGui.QComboBox(self.centralwidget)
        self.so_box.setEnabled(True)
        self.so_box.setObjectName(_fromUtf8("so_box"))
        self.verticalLayout_5.addWidget(self.so_box)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.texts = QtGui.QVBoxLayout()
        self.texts.setObjectName(_fromUtf8("texts"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.station_label = QtGui.QLineEdit(self.centralwidget)
        self.station_label.setObjectName(_fromUtf8("station_label"))
        self.verticalLayout_3.addWidget(self.station_label)
        self.verticalLayout_9.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.text_message = QtGui.QLineEdit(self.centralwidget)
        self.text_message.setObjectName(_fromUtf8("text_message"))
        self.verticalLayout_4.addWidget(self.text_message)
        self.verticalLayout_9.addLayout(self.verticalLayout_4)
        self.texts.addLayout(self.verticalLayout_9)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.texts.addItem(spacerItem5)
        self.transmissionOptionsBtn = QtGui.QPushButton(self.centralwidget)
        self.transmissionOptionsBtn.setObjectName(_fromUtf8("transmissionOptionsBtn"))
        self.texts.addWidget(self.transmissionOptionsBtn)
        spacerItem6 = QtGui.QSpacerItem(20, 43, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.texts.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.texts)
        self.audio_file = QtGui.QVBoxLayout()
        self.audio_file.setObjectName(_fromUtf8("audio_file"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.audio_file.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.audio_file.addWidget(self.label_8)
        self.verticalLayout_2.addLayout(self.audio_file)
        self.path_folder = QtGui.QHBoxLayout()
        self.path_folder.setObjectName(_fromUtf8("path_folder"))
        self.file_path = QtGui.QLineEdit(self.centralwidget)
        self.file_path.setEnabled(False)
        self.file_path.setObjectName(_fromUtf8("file_path"))
        self.path_folder.addWidget(self.file_path)
        self.search_file_btn = QtGui.QPushButton(self.centralwidget)
        self.search_file_btn.setEnabled(True)
        self.search_file_btn.setObjectName(_fromUtf8("search_file_btn"))
        self.path_folder.addWidget(self.search_file_btn)
        self.verticalLayout_2.addLayout(self.path_folder)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.audiosamp = QtGui.QVBoxLayout()
        self.audiosamp.setObjectName(_fromUtf8("audiosamp"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.audiosamp.addWidget(self.label_9)
        self.audio_samp = QtGui.QComboBox(self.centralwidget)
        self.audio_samp.setObjectName(_fromUtf8("audio_samp"))
        self.audiosamp.addWidget(self.audio_samp)
        self.horizontalLayout_4.addLayout(self.audiosamp)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.pulse_check = QtGui.QCheckBox(self.centralwidget)
        self.pulse_check.setObjectName(_fromUtf8("pulse_check"))
        self.horizontalLayout_4.addWidget(self.pulse_check)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.start_btn = QtGui.QPushButton(self.centralwidget)
        self.start_btn.setObjectName(_fromUtf8("start_btn"))
        self.horizontalLayout.addWidget(self.start_btn)
        self.stop_btn = QtGui.QPushButton(self.centralwidget)
        self.stop_btn.setEnabled(True)
        self.stop_btn.setObjectName(_fromUtf8("stop_btn"))
        self.stop_btn.hide()
        self.horizontalLayout.addWidget(self.stop_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 531, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Settings = QtGui.QMenu(self.menubar)
        self.menu_Settings.setObjectName(_fromUtf8("menu_Settings"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        self.menu_About = QtGui.QMenu(self.menubar)
        self.menu_About.setObjectName(_fromUtf8("menu_About"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.action_Exit_Alt_F4 = QtGui.QAction(MainWindow)
        self.action_Exit_Alt_F4.setObjectName(_fromUtf8("action_Exit_Alt_F4"))
        self.actionTransmission_Options = QtGui.QAction(MainWindow)
        self.actionTransmission_Options.setObjectName(_fromUtf8("actionTransmission_Options"))
        self.actionAudio_Spectrum = QtGui.QAction(MainWindow)
        self.actionAudio_Spectrum.setObjectName(_fromUtf8("actionAudio_Spectrum"))
        self.actionOFDM_Spectrum = QtGui.QAction(MainWindow)
        self.actionOFDM_Spectrum.setObjectName(_fromUtf8("actionOFDM_Spectrum"))
        self.actionCombined_View = QtGui.QAction(MainWindow)
        self.actionCombined_View.setObjectName(_fromUtf8("actionCombined_View"))
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit_Alt_F4)
        self.menu_Settings.addAction(self.actionTransmission_Options)
        self.menu_View.addAction(self.actionAudio_Spectrum)
        self.menu_View.addAction(self.actionOFDM_Spectrum)
        self.menu_View.addAction(self.actionCombined_View)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Settings.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.start_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.stop_btn.show)
        QtCore.QObject.connect(self.start_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.start_btn.hide)
        QtCore.QObject.connect(self.stop_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.start_btn.show)
        QtCore.QObject.connect(self.stop_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.stop_btn.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.main_label.setText(_translate("MainWindow", "Transmission Parameters", None))
        self.groupBox.setTitle(_translate("MainWindow", "MSC Modulation", None))
        self.msc_16.setText(_translate("MainWindow", "16 QAM", None))
        self.msc_64.setText(_translate("MainWindow", "64 QAM", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "SDC Modulation", None))
        self.sdc_4.setText(_translate("MainWindow", "4 QAM", None))
        self.sdc_16.setText(_translate("MainWindow", "16 QAM", None))
        self.rm_label.setText(_translate("MainWindow", "RM", None))
        self.so_label.setText(_translate("MainWindow", "SO", None))
        self.label_5.setText(_translate("MainWindow", "Station Label", None))
        self.label_6.setText(_translate("MainWindow", "Text Message", None))
        self.transmissionOptionsBtn.setText(_translate("MainWindow", "Transmission Options", None))
        self.label_7.setText(_translate("MainWindow", "Audio File", None))
        self.label_8.setText(_translate("MainWindow", "Path", None))
        self.search_file_btn.setText(_translate("MainWindow", "Search file", None))
        self.label_9.setText(_translate("MainWindow", "Audio sample rate [kHz]", None))
        self.pulse_check.setText(_translate("MainWindow", "Use PulseAudio Output", None))
        self.start_btn.setText(_translate("MainWindow", "Start Transmission", None))
        self.stop_btn.setText(_translate("MainWindow", "Stop Transmission", None))
        self.stop_btn.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Settings.setTitle(_translate("MainWindow", "&Settings", None))
        self.menu_View.setTitle(_translate("MainWindow", "&View", None))
        self.menu_About.setTitle(_translate("MainWindow", "&About", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.action_Exit_Alt_F4.setText(_translate("MainWindow", "&Exit       Alt +F4", None))
        self.actionTransmission_Options.setText(_translate("MainWindow", "Transmission Options", None))
        self.actionAudio_Spectrum.setText(_translate("MainWindow", "Audio Spectrum", None))
        self.actionOFDM_Spectrum.setText(_translate("MainWindow", "OFDM Spectrum", None))
        self.actionCombined_View.setText(_translate("MainWindow", "Combined View", None))

