#  Faad_INCLUDE_DIRS - where to find neaacdec.h, etc.
#  Faad_LIBRARY_DIRS    - List of libraries when using libfaad.
#  Faad_FOUND        - True if libfaad found.

# Look for the header file.
FIND_PATH(FAAD_INCLUDE_DIR NAMES neaacdec.h)
MARK_AS_ADVANCED(FAAD_INCLUDE_DIR)

# Look for the library.
FIND_LIBRARY(FAAD_LIBRARY NAMES faad)
MARK_AS_ADVANCED(FAAD_LIBRARY)

# Copy the results to the output variables.
IF(FAAD_INCLUDE_DIR AND FAAD_LIBRARY)
  SET(Faad_FOUND 1)
  SET(Faad_LIBRARY_DIRS ${FAAD_LIBRARY})
  SET(Faad_INCLUDE_DIRS ${FAAD_INCLUDE_DIR})
ELSE(FAAD_INCLUDE_DIR AND FAAD_LIBRARY)
  SET(Faad_FOUND 0)
  SET(Faad_LIBRARY_DIRS)
  SET(Faad_INCLUDE_DIRS)
ENDIF(FAAD_INCLUDE_DIR AND FAAD_LIBRARY)

# Report the results.
IF(NOT Faad_FOUND)
  SET(FAAD_DIR_MESSAGE
    "FAAD was not found. Make sure FAAD_LIBRARY and FAAD_INCLUDE_DIR are set.")
  IF(NOT FAAD_FIND_QUIETLY)
    MESSAGE(STATUS "${FAAD_DIR_MESSAGE}")
  ELSE(NOT FAAD_FIND_QUIETLY)
    IF(FAAD_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "${FAAD_DIR_MESSAGE}")
    ENDIF(FAAD_FIND_REQUIRED)
  ENDIF(NOT FAAD_FIND_QUIETLY)
ENDIF(NOT Faad_FOUND)
